version: "3"
services:
  portfolio_app:
    image: nginx:latest
    container_name: "portfolio_app"
    environment:    
        VIRTUAL_HOST: ${FRONT_HOST}
        LETSENCRYPT_HOST: ${FRONT_HOST}
        LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always
    volumes:
      - ./main/nginx/app:/app
      - ./main/nginx/default.conf:/etc/nginx/conf.d/default.conf 

networks:
  default:
    external:
      name: shared